### ISSUE TITLE
Issue while building ROS2 package

### ISSUE THREAD

**Issue by Akshay-9416** [ament/ament_package#125]
Hello,
I am trying to write my own package in ROS2. while building I got errors related to ament_package. 
please refer to the below screenshot and let me know what needs to be done or If I am doing any mistake.

Thank you.

![image](https://user-images.githubusercontent.com/60077708/105485350-bf75fb80-5cd2-11eb-824b-5454be24c21f.png)

**Comment by tfoote** [comment]
Please ask for help on answers.ros.org following our support guidelines https://wiki.ros.org/Support

When you ask your question there please make sure to provide enough description that the potential person answering your question can reproduce it including the steps that you did to set up your workspace and package as well as all the exact commands that you ran. And when you do this copy and past the text output so the text is searchable instead of screenshots.
