### ISSUE TITLE
setup.bash fails

### ISSUE THREAD

**Issue by tfoote** [ament/ament_package#28]
In RC2: 

```
$ . setup.bash
bash: /usr/bin/env python3: No such file or directory
```
That does evaluate to python3 for me, however I think the error is that the whole string is being passed to bash as a single command instead of being parsed by the command line options. 

local_setup.bash works fine. 

@jacquelinekay has also incountered this

**Comment by gerkey** [comment]
The problem is with the [setting of IFS](https://github.com/ament/ament_package/blob/master/ament_package/template/prefix_level/setup.sh.in#L110), which apparently carries through to files that are sourced, in turn affecting how strings of arguments get expanded in commands.

@dirk-thomas is working on a fix.

**Comment by gerkey** [comment]
The [latest packaging job binary](http://ci.ros2.org/view/packaging/job/ros2_packaging_linux/43/) works for me.
