### ISSUE TITLE
the INCLUDE_DIRS generated by ament_package are duplicated

### ISSUE THREAD

**Issue by tfoote** [ament/ament_package#31]
I added the following debug message

I'm using 
```
cmake_minimum_required(VERSION 2.8.3)
project(tf2)

find_package(ament_cmake)
find_package(geometry_msgs REQUIRED)

message(WARNING "geometry_msgs_INCLUDE_DIRS is: [[${geometry_msgs_INCLUDE_DIRS}]]")
```

And it appears that the geometry_msgs_INCLUDE_DIRS has 3 identical entries. 

```
CMake Warning at CMakeLists.txt:16 (message):
  geometry_msgs_INCLUDE_DIRS is:
  [[/home/tfoote/work/ros2/tf3/install/include;/home/tfoote/work/ros2/tf3/install/include;/home/tfoote/work/ros2/tf3/install/include]]
```

**Comment by dirk-thomas** [comment]
`ament_package` is a pure Python package parsing manifest file. This belong in the `ament_cmake` repo since it is a CMake specific problem.

Since the exported information of each package in the generated CMake code look reasonable (without duplicates) it is likely related to aggregating information from recursive dependencies: https://github.com/ament/ament_cmake/blob/master/ament_cmake_export_dependencies/cmake/ament_cmake_export_dependencies-extras.cmake.in
PR ament/ament_cmake#47 should get rid of these duplicates.
