### ISSUE TITLE
use PATH to find for python in Windows

### ISSUE THREAD

**Issue by geoffviola** [ament/ament_package#43]
I noticed that in https://github.com/ament/ament_package/blob/ce7284cad427065d510484850be936226fdae9c2/ament_package/template/prefix_level/local_setup.bat.in#L26, the order to find python is C:\ProgramData\chocolatey\lib\python3\tools\python.exe (in the binary ros2-windows alpha8 release) and then the AMENT_PYTHON_EXECUTABLE variable. Also, when it fails to find python it just prints out something generic cannot find executable.

I think it makes more sense to search the AMENT_PYTHON_EXECUTABLE variable, then whatever hard coded path the binary release has, and then the PATH variable for python. There may be a similar issue with Linux, but I'm more concerned with Windows right now.

**Comment by wjwwood** [comment]
I don't read the code that way, though there may be a bug there. I think the code is trying to do:

- set `ament_python_executable` to the compile time location of Python, i.e. `@PYTHON_EXECUTABLE@`
- if externally set, i.e. `%AMENT_PYTHON_EXECUTABLE%` is not empty, then assign that to `ament_python_executable`

That would mean that `%AMENT_PYTHON_EXECUTABLE%` would always take precedent. However, I think there might be a bug here since `%AMENT_PYTHON_EXECUTABLE%` and `ament_python_executable` are the same variable (Windows batch env vars are case-insensitive).

**Comment by geoffviola** [comment]
You're right, it looks like the later lines use %AMENT_PYTHON_EXECUTABLE% to overwrite ament_python_executable.

I'm proposing having a check if the compile time location of Python exists and then trying to set it to python through the PATH variable. Also, it would do an error check if it is not there. Does that sounds beneficial? Basically, I want to be able to manually install python via the direct installer or anaconda instead of just chocolatey.

**Comment by dirk-thomas** [comment]
Addressed by #45.
