### ISSUE TITLE
add a way to skip building packages conditionally

### ISSUE THREAD

**Issue by BrannonKing** [ament/ament_package#61]
Is it possible for the Ament build system to skip building a package if a different package exists? Maybe two packages do similar things and the second one shouldn't be built if the first one exists. My example: sometimes I package the DDS binaries and sometimes not. If the DDS binaries are not included then I want to include a different package that knows where to look for them and/or ensures the appropriate environment variables.

**Comment by BrannonKing** [comment]
As a corollary, I suppose that other packages would need the ability to depend upon "one or the other" package.

**Comment by BrannonKing** [comment]
I realized that it was the "find_package" calls in CMakeLists.txt that were blocking the build; dependencies are already optional.

**Comment by dirk-thomas** [comment]
For the dependencies in the manifest a design article is in-progress which aims to support the concept of "provides" (ros2/design#138).

Regarding the CMake file that is probably nothing "ament" can do for you but the specific `CMakeLists.txt` would need to implement that "either or" logic. I don't think we have a any packages doing exactly that. Some of the package gracefully fall back if their dependencies are not met (e.g. https://github.com/ros2/rmw_connext/blob/0c747ae26530d33aabc15aa4bf1f8b39cf7c13e6/rmw_connext_cpp/CMakeLists.txt#L19-L29).

**Comment by mikaelarguedas** [comment]
@BrannonKing Can you comment on the referenced [design document PR](https://github.com/ros2/design/pull/138) if it meets or doesn't meet your needs in order to achieve this ?

**Comment by BrannonKing** [comment]
The document does satisfy my needs. Alternatively, have you also considered having a package declare that it "is a dependecy of" some other package?

**Comment by dirk-thomas** [comment]
> have you also considered having a package declare that it "is a dependecy of" some other package?

I guess the dependency groups makes this case more explicit since the other package has to explicitly allow that by declaring the dependency group. But I can see your case where it would be more convenient to do this without the "other" package declaring the group.

On the other hand it might be easily abused. A package could declare to be a run dependency of `roscpp` and based on that it would always be installed when `roscpp` is installed. Though the same is true for the dependency groups - any package could declare to be member of "message generation" group (without actually being a message generator) and would be pulled in during installation of the ROS core packages.

We will think about the pros and cons to allow declaring such a dependency without changing the "other" package...

**Comment by dirk-thomas** [comment]
Since we don't consider "injecting" dependencies to be a good idea and the REP 149 (which has been implemented by now) satisfies your use case I will go ahead and close this. Please feel free to continue commenting.
