### ISSUE TITLE
LD_LIBRARY_PATH support for packages using gnuinstalldirs

### ISSUE THREAD

**Issue by nuclearsandwich** [ament/ament_package#68]
Some packages install their shared libraries into /opt/ros/$ROSDISTRO/lib/x86_64-linux-gnu rather than the prefix-level lib directory directly.

The library_path environment hook will only add the lib directory of the `AMENT_CURRENT_PREFIX`.

https://github.com/ament/ament_package/blob/5a4d070b0cf28e2ce0acb231507a59d4756b5566/ament_package/template/environment_hook/library_path.sh#L11-L14

In the immediate term I'm looking for the most straightforward way for my ros_workspace package to shoehorn in an environment hook that prepends the multiarch triplet (obtainable on Linux by `dpkg-architecture -qDEB_HOST_MULTIARCH` or `gcc -dumpmachine`).

In the long term I suppose we should determine how ament can observe the use of this directories and generate hook scripts appropriately.

**Comment by wjwwood** [comment]
Potentially related or useful: https://github.com/ros/catkin/issues/545

**Comment by nuclearsandwich** [comment]
For ardent I was able to hack something together, so while we should advance this discussion and find a way to integrate support for this, it doesn't affect the release.

**Comment by dirk-thomas** [comment]
If it would be a package using `ament_cmake` it could simply register an environment hook to export the necessary environment variable change. If it is a plain CMake package there is nothing `ament_cmake` can do for it. Also the build tool `ament_tools` can't provide support for this since it is not being used in the release process to build Debian packages. Therefore can you please clarify which packages this affects and what the scope of this issue should be (I don't see any actionable task in ament atm).

> For ardent I was able to hack something together

It would be good to reference the applied hack here. First so that others reading thi are aware how it is being worked around atm. Second to avoid that we run into the same problem again during the next release since the hack is hidden in some release repo.

**Comment by nuclearsandwich** [comment]
When I opened this issue, I thought that there was more to the librarypath environment hook than any other environment hook registered by an ament package. Consequently I opened this issue since the librarypath hook doesn't support paths other than `$PREFIX/lib`.

I'm also unclear why packages like urdfdom and class_loader install into `$PREFIX/lib` in from-source builds with ament_tools but that's a somewhat orthogonal question since clearly they're installing to an accessible location and so do not need environment hook changes except for the Debian builds.

So the answer to my question is that multiarch directory structure support for ament can be handled by regular ament environment hooks and no apparent special handling is needed by ament_package or ament_tools.
