### ISSUE TITLE
Change sorting of environment hooks

### ISSUE THREAD

**Issue by wjwwood** [ament/ament_package#7]
See: https://github.com/ament/ament_package/pull/6#issue-60469101

AC:

- ~~Environment hooks are executed in sorted order based on their _file_ name first then their full path in the case of ties.~~

**Comment by dirk-thomas** [comment]
Instead of ordering all environ hooks based on their basename across packages on Windows I will update the Linux behavior to source the environment of each package in topological order of the packages.

If we invoke Python for this the prefix level setup file will be a bit slower. But the result will be the same environment as for an isolated build. We can refactor the ordering into shell / batch code if the performance improvement is worth it.

**Comment by dirk-thomas** [comment]
Since the overhead for calling Python is only linear in the number of unique parent prefix paths and not with the number of upstream packages I won't implement the ordering in shell code for now.
