### ISSUE TITLE
I can't build ros2 with the latest code of master branch

### ISSUE THREAD

**Issue by xhuan28** [ament/ament_package#76]
I was trying to build ros2 from source code, but met the following errors:

Traceback (most recent call last):
  File "src/ament/ament_tools/scripts/ament.py", line 139, in <module>
    from ament_tools.package_types.ament import entry_point_data as ament_entry_point_data  # noqa
  File "/home/robot/workspace/ros2_ws_cov_2018-06-07/src/ament/ament_tools/ament_tools/package_types/ament.py", line 15, in <module>
    from ament_package import package_exists_at
ImportError: cannot import name 'package_exists_at'

The build steps are:
mkdir -p ~/ros2_ws/src
cd ~/ros2_ws
wget https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
vcs-import src < ros2.repos
cd ~/ros2_ws/
src/ament/ament_tools/scripts/ament.py build --build-tests --symlink-install

There is no such build issue on release-latest branch.

**Comment by dirk-thomas** [comment]
Thank you for reporting the problem. We have recently switched to use the new universal build tool (as described in ros2/design#168) and don't use `ament_tools` actively anymore. But the wiki currently still invokes `ament_tools` in the instructions.

As of #75 all Python modules except the templates have been removed from this package. Instead the modules of the Python package `catkin_pkg` should be used. Since we didn't use `ament_tools` anymore we didn't notice that it needs update to.

Can you please try the `ament_tools` branch from ament/ament_tools#188. That should hopefully make it work again for now.

**Comment by xhuan28** [comment]
Thanks for your prompt fix. Build works now with the branch of use_catkin_pkg.
